# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(blank=True, default=1, null=True, verbose_name='Serial Number')),
                ('resume', models.BooleanField(default=False, verbose_name='Is having Resume')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Candidate Name')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Candidate Email')),
                ('experience', models.FloatField(blank=True, null=True, verbose_name='Work experience')),
                ('analytics_experience', models.FloatField(blank=True, null=True, verbose_name='Analytics in Experience')),
                ('current_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='current location')),
                ('corrected_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='corrected location')),
                ('nearest_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='nearest city')),
                ('ctc', models.FloatField(blank=True, null=True, verbose_name='CTC')),
                ('current_employer', models.CharField(blank=True, max_length=255, null=True, verbose_name='current employer')),
                ('current_designation', models.CharField(blank=True, max_length=255, null=True, verbose_name='current employer')),
                ('ug', models.CharField(blank=True, max_length=255, null=True, verbose_name='UG courses')),
                ('ug_inst', models.CharField(blank=True, max_length=255, null=True, verbose_name='UG institution name')),
                ('ug_year', models.CharField(blank=True, max_length=255, null=True, verbose_name='UG year of Passing')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='City Name')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=255, null=True, verbose_name='Skill Name')),
            ],
        ),
        migrations.AddField(
            model_name='candidatedetails',
            name='preferred_location',
            field=models.ManyToManyField(blank=True, related_name='city', to='recruiter.Location'),
        ),
        migrations.AddField(
            model_name='candidatedetails',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='city', to='recruiter.Skills'),
        ),
    ]
