# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-10 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedetails',
            name='ctc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CTC'),
        ),
        migrations.AlterField(
            model_name='candidatedetails',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Work experience'),
        ),
    ]
