# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-10 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_auto_20180710_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedetails',
            name='ctc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='CTC'),
        ),
        migrations.AlterField(
            model_name='candidatedetails',
            name='experience',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Work experience'),
        ),
    ]
